services:
  web:
    image: "luc004/mini-project:latest"
    ports:
      - "5000:5000"
    environment:
      - APP_TITLE=Le Dashboard de Génie de Luc
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data  # On branche le disque dur virtuel ici

volumes:
  redis_data:             # On déclare le volume