services:
  web:
    image: "luc004/mini-project:latest"
    ports:
      - "5000:5000"
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
  redis:
    image: "redis:alpine"
    command: 
    - redis-server --requirepass 1234
    - redis_data:/data  # On branche le disque dur virtuel ici

volumes:
  redis_data:             # On d√©clare le volume