services:
  web:
    image: "luc004/mini-project:latest"
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data  # On branche le disque dur virtuel ici

volumes:
  redis_data:             # On d√©clare le volume