services:
  web:
    image: "luc004/mini-project:latest"
    ports:
      - "5000:5000"
    environment:
     environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - APP_TITLE=${APP_TITLE}
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass mon_mot_de_passe_secret
    volumes:
      - redis_data:/data  # On branche le disque dur virtuel ici

volumes:
  redis_data:             # On d√©clare le volume