services:
  web:
    image: "luc004/mini-project:latest"
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - APP_TITLE=${APP_TITLE}
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    # Correction ici : la commande doit être sur une seule ligne
    command: redis-server --requirepass ${REDIS_PASSWORD}
    # Correction ici : volumes doit être une section à part
    volumes:
      - redis_data:/data

volumes:
  redis_data: